### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-html-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://abundant-motion.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/html-intro/1) criteria:
- [x] Use at least one `h1` element.
- [x] Use at least one `a` element.
- [x] Use at least one `p` element.
- [x] Use at least one `img` element.
- [x] Use at least one `ul` element.
- [x] Use at least one `li` element.
- [x] When you paste the address of your website into [the W3C validator](https://validator.w3.org/), it returns no errors (warnings are OK).
- [x] This is the last time I'll mention it, but once again, your project should be on GitHub and hosted online (I recommend using surge again).

**Comment by chrisvfritz** [comment]
It looks like the link to the hosted URL (on surge) isn't working. Are you sure you published the latest version with `surge --domain abundant-motion.surge.sh`? 

Looking at the code though, it looks like you've gone above and beyond on this project! Not only do you have the elements, but classes and CSS as well! And completely consistent indentation, which is something many students struggle with early one. :tada: The only issues I can find are some tiny formatting/style things.

### Remove empty CSS selectors

You can [an empty CSS selector here](https://github.com/ackleyd1/codelab-html-intro/blob/master/index.html#L6-L7). If we're not using it, let's just remove it.

### Make consistent use of empty lines

I notice you're including empty lines after the opening block of CSS selectors [sometimes](https://github.com/ackleyd1/codelab-html-intro/blob/master/index.html#L10), but not others. Let's remove those extra lines unless you have a good reason for them in those cases.

---

Let me know with a comment here when you've made these updates, both on GitHub and surge, then I'll take another look!

**Comment by ackleyd1** [comment]
Hmm that surge issue was strange. It should be up on http://perpetual-grandfather.surge.sh/ now. I also updated those code lines. Thanks for the feedback! The only reason I had CSS as a part of this intro was because I had gone ahead and already edited my html file with the next section before I created initialized my git repository for this one. So thats why the two look the exact same.

**Comment by ackleyd1** [comment]
Also I got real used to indentation in Python which I learned over the summer. One of my brothers friends said Python was good for a beginner language and getting people used to indenting and formatting code correctly in particular.

**Comment by chrisvfritz** [comment]
Your brother's friend is right. :smiley: Python is also in many ways similar to Ruby, so some of those skills should transfer when you start on that!

This looks fantastic now. :tada: :shipit:
